name: fuck_qqmusic
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  path: ^1.9.0
  http: ^1.2.2
  dio: ^5.7.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
