name: fuck_neteasemusic
description: A sample command-line application.
version: 1.2.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  encrypt: ^5.0.3
  hex: ^0.2.0
  path: ^1.9.0
  crypto: ^3.0.5
  dio: ^5.7.0
  pointycastle: ^3.9.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
